spring.application.name=SoccerRest
# PostgreSQL
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/soccer_rest}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:123456}
spring.datasource.driver-class-name=${JDBC_DATABASE_DRIVER:org.postgresql.Driver}
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
# OpenAPI / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
